"""
Django settings for streaming_backend project.

Generated by 'django-admin startproject' using Django 4.2.29.
"""

from pathlib import Path

# ==========================================
# BASE DIR
# ==========================================
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================================
# SECURITY
# ==========================================
SECRET_KEY = 'django-insecure-+2owgw2si5e84*r6d0+j22c8j@g+=04nnvg&lvz0%)ao!b$=ga'

DEBUG = True

ALLOWED_HOSTS = []


# ==========================================
# APPLICATIONS
# ==========================================
INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Librerías externas
    'rest_framework',
    'corsheaders',
    'drf_spectacular',

    # Apps propias
    'users',
    'core',
]


# ==========================================
# MIDDLEWARE
# ==========================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==========================================
# URLS / WSGI
# ==========================================
ROOT_URLCONF = 'streaming_backend.urls'

WSGI_APPLICATION = 'streaming_backend.wsgi.application'


# ==========================================
# TEMPLATES
# ==========================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ==========================================
# DATABASE
# ==========================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'streaming_db',
        'USER': 'postgres',
        'PASSWORD': 'gabriel98',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# ==========================================
# CUSTOM USER MODEL
# ==========================================
AUTH_USER_MODEL = 'users.User'


# ==========================================
# PASSWORD VALIDATION
# ==========================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==========================================
# INTERNATIONALIZATION
# ==========================================
LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Mendoza'

USE_I18N = True

USE_TZ = True


# ==========================================
# STATIC FILES
# ==========================================
STATIC_URL = 'static/'


# ==========================================
# DEFAULT PRIMARY KEY
# ==========================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# CORS
# ==========================================
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
]


# ==========================================
# DJANGO REST FRAMEWORK
# ==========================================
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Opcional pero recomendado
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}


# ==========================================
# SWAGGER / OPENAPI
# ==========================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'Streaming API',
    'DESCRIPTION': 'API de usuarios, contenidos y visualizaciones',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# ==========================================
# LOGGING (opcional, útil para debug y producción)
# ==========================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
}