@startuml
title Sistema de Cine y Streaming - Diagrama ER

entity Usuarios {
  + id_usuario : INT <<PK>>
  --
  nombre : VARCHAR
  email : VARCHAR
  fecha_registro : DATE
}

entity Creadores {
  + id_creador : INT <<PK>>
  --
  nombre : VARCHAR
  email : VARCHAR
}

entity Contenido {
  + id_contenido : INT <<PK>>
  --
  titulo : VARCHAR
  tipo : VARCHAR
  genero : VARCHAR
  año : INT
  duracion_min : INT
  id_creador : INT <<FK>>
}

entity Visualizaciones {
  + id_visualizacion : INT <<PK>>
  --
  id_usuario : INT <<FK>>
  id_contenido : INT <<FK>>
  fecha_visualizacion : DATE
}

Usuarios ||--o{ Visualizaciones : realiza
Contenido ||--o{ Visualizaciones : tiene
Creadores ||--o{ Contenido : publica

@enduml